### ISSUE TITLE
It this normal speed?

### ISSUE THREAD

**Issue by pondloso** [kijai/ComfyUI-CogVideoXWrapper#66] opened 2024-09-19 10:02 UTC
cog 5b i2v
16 vram
 33.67s/it

30 step took me like 18-19 min

if i remember  cog 5b t2i much quicker than this.

and for some reason  Cog-fun always want to fine closes size from image not real image size  input
it always in wrong size .

and how much vram need for 768 base resolution?

I just want to check that every thing is right for my install,it seem take to much longer than i expect.

Thank you for you great work as always.

**Comment by Felipe-Rafael-Rosa** [comment] 2024-09-19 10:18
install this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by rhystz** [comment] 2024-09-19 10:34
I'm getting the same it/s on a 16gb rtx a4500 mobile. I've got another comfy install with different pytorch that's almost twice as slow.

I'm also finding that differences in overall image quality and facial and finger cohesion are pretty small between 9 and 50 steps. At 50 steps tho i'd say its right on par with the current 5b-i2v hugging space.

**Comment by pondloso** [comment] 2024-09-19 10:38
> Which GPU? Doesn't sound normal at all, check your VRAM usage to see how close it is to the max, the nvidia system memory fallback might be triggering and slowing it down.
> 
> CogVideoX-Fun is designed like that, it finds the closest resolution it was trained with.
> 
> I don't know the exact VRAM requirements for each dimension, but I'd guess 768 is something like 20GB+

4061ti 16gb
after open up comfy is will use around 1.3-1.5  gb of vram
when it process it use nearly all of it and when  it decode it will had to use share vram so i had to wait like a minute extra just for decode .

I'm also think this is not normal but i cant find what i do wrong.

**Comment by pondloso** [comment] 2024-09-19 11:27
i want to report another test.
I test  CogVideoX-Fun  2b it very fast
10 step look almost same with 20 step,10 steps it finish in just 1 minute.

when is process it use just 6 gb of vram but when it decode it even overflow my 16 gb of vram.
CogVideoX-Fun  2b it look like had a great potential with speed but had to see about quality.

**Comment by ArtemKo7v** [comment] 2024-09-19 11:57
CogVideoX 5b i2v
4070Ti 12gb
~25s/it

It takes about 20 minutes to generate i2v with 50 steps with enable_sequential_cpu_offload=true
Besides it uses only 2-5 gb of vram during the sampling, and gpu utilization does not exceed 30%, which tells me that there is room for optimization and it could potentially run noticeably faster.

**Comment by morganavr** [comment] 2024-09-19 13:40
CogVideoX 5b i2v
3080 10gb

10 minutes already passed and terminal in Windows 10 still shows **0/50**
I used this workflow: examples/cogvideox_I2V_example_01.json

![image](https://github.com/user-attachments/assets/943dd535-3567-4bdb-832c-6e8403343176)

**Comment by kijai** [comment] 2024-09-19 14:03
> CogVideoX 5b i2v 3080 10gb
> 
> 10 minutes already passed and terminal in Windows 10 still shows **0/50** I used this workflow: examples/cogvideox_I2V_example_01.json
> 
> ![image](https://private-user-images.githubusercontent.com/51041813/369017488-943dd535-3567-4bdb-832c-6e8403343176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTQ4MjIsIm5iZiI6MTcyNjc1NDUyMiwicGF0aCI6Ii81MTA0MTgxMy8zNjkwMTc0ODgtOTQzZGQ1MzUtMzU2Ny00YmRiLTgzMmMtNmU4NDAzMzQzMTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE0MDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyODkzNmIyOTc0MTRlOWY1Y2E4Y2NkNzVkOWM5MjczYmQyYmZlOTQ4ZGE2MTcxNjVjZmM4ODZkNWY0YTc5YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5NhmwVx13mFG-jRYS9j3AsF0W44_dPAukc3CWP2WrlY)

10GB is probably not gonna be enough without sequential_cpu_offloading

**Comment by morganavr** [comment] 2024-09-19 14:16
Thanks for suggestion but it did not help.

I tried a different workflow (cogvidex_fun_i2v_example_01) but result is the same - there is no progress for 10 minutes. Still 0/30

`sequential_cpu_offloading` is enabled

![image](https://github.com/user-attachments/assets/a062e830-539c-4c9a-a152-886299ef8b88)

**Comment by morganavr** [comment] 2024-09-19 14:40
12 minutes later only one iteration is done.  728.32s/it.

  3%|██▋                                                                             | 1/30 [12:08<5:52:01, 728.32s/it]

**Comment by alphatest8422** [comment] 2024-09-19 15:18
The CogVideoX authors mention that cpu offloading is incredibly slow. They added in there to support lower end machines on colab, but mention in their repository that the byproduct is incredibly slow generation times and that there is currently no workaround for this. So if you're using enable_sequential_cpu_offload=true, expect some painfully long generations.

**Comment by KrakeyMTL** [comment] 2024-09-19 15:43
About 10min here using the comfyui interface on an A6000 gpu. This is on par with using comfy and the 2B text to video model so I would say I2V same speeds. So if you test the 2B and get a certain speed - copy the same switches (all off really) and re-run to match in the i2v

Note: running this command line non-comfyui nets you roughly 8min if all configured properly. I posted all the various GPU speeds in the 2B main question thread (still opened in that forum)

![image to video I2V sample 1](https://github.com/user-attachments/assets/8b048ae2-30cf-4104-8cf1-ae812f6ee82c)

**Comment by synystersocks** [comment] 2024-09-19 15:48
the speed loss for cpu off loading is because of transfer of data back and forth, aswel as read/write operations. vram capacity isnt really the issue, its getting the data to the cores fast enough, big vram is just our best solution currently (the us department of energy recently released a paper on supercluster parrelization in which they retimed the data flow to compensate/optimaise for this loss, strange paper tho cough cough nvidia bias :P), when you look at gpu design you can see how close the vram is to the cache and how cache scales down as it gets closer to the cores, this is because charge "electrons" are bound by the speed of quanta (speed of light), the distance data has to travel cost time, apu's with shared cpu/gpus kinda get around this, yet the cycle speeds arent enought to really benifit them yet. its the same as lag from servers, its all physics baby :D

**Comment by KrakeyMTL** [comment] 2024-09-19 16:00
CROSS POST LINKS FOR THE INFO ON SPEEDS AND VRAM

NOTE: these links will take you to the same company 2B model where we just recently had a huge discussion on all this. It will help shed light on the vram and swapping switches stuff above!

https://huggingface.co/THUDM/CogVideoX-5b/discussions/7 (open. not mine. info near bottom last post)

https://huggingface.co/THUDM/CogVideoX-5b/discussions/8 (closed by me. completed)

**Comment by pondloso** [comment] 2024-09-19 22:20
> Disable all of these things in fuchsia color - NOTE I have 48GB vram on the a6000 so I am able to do this. IF YOU HAVE LESS THAN 24GB vram this probably will break! and you'll need to at least enable one of the memory saving switches.
> 
 
> 
> edit: 3rd note: that image was from my own custom sdxl model, and is actually 1200x1200 natural gen sizing which SDV2 can easily animate without sizing restrictions like this model has. fyi!
> 
 What is  SDV2 ?

**Comment by KrakeyMTL** [comment] 2024-09-22 19:51
> What is SDV2 ?

Essentially stable diffusion video version 2, and no for the next question. Not yet. ;) 
IF they release it's on them. I didn't wait took the 1.1 and modified it to make my own custom version - calling it my own V2 LOL

attached are a few samples. you might recognize if you are part of a certain discord server hehe.

If I'm honest it beats the image2vid here only because I can use my own custom resolutions. In these videos it's taking 1024x1024 and animating them - and I've already done 1920x1080 conversions it works just fine as well - vastly superior to the current I2V here for quality and pushing the sizing limits (naturally). Where it falls flat is the motion control and dynamic video prompting.

That's the trade off in the end.

//these samples are not i2v - but a custom large format model for text 2 image used then converted as stated above.//

https://github.com/user-attachments/assets/ef3a972c-1554-443d-a20a-729810080181
https://github.com/user-attachments/assets/01ce6231-62c2-47dd-b067-28a279729025
https://github.com/user-attachments/assets/746e51c7-9c58-4eaf-b507-186a81b70bbe
https://github.com/user-attachments/assets/d7142384-53b9-49f5-b1c8-0f82162994e4
https://github.com/user-attachments/assets/2db7ac57-b26e-45cc-8ca9-ba433e6ef35a
https://github.com/user-attachments/assets/bffc1817-06d4-4591-be6a-829837e5c213

**Comment by rktvr** [comment] 2024-09-24 07:21
it takes me around 18 minutes for an i2v with fun/normal cog 5b on a 3090. that can't be normal, right? it ranges on anything between 9 to 15s/it.

there are so many people saying it only takes them 1 minute but surely they can't be right

**Comment by KrakeyMTL** [comment] 2024-09-24 14:08
I'm not sure why people are stating the 50 steps are overkill. Doesn't seem like that too me as the results are worst for me with less steps. And the number of steps will only drop your time by so much - the machine still needs to go through the motions of loading, offloading, VAE etc where the big hits come from.

Unless you are running the same workflow, or post up YOUR workflow for others to try and run - we cannot help for speeds more as there are so many variables.

As above, some of us CAN tell you that across multiple GPU's from L40's to A6000 chips (which are pro versions of your home cars the 3090's and 4090 etc..) yes yes I know - but you know what I mean. Gotta love nvidia...

On these chips the speeds are around 8-11 s/it for the "example" dog sunglasses workflow @ default 50 steps etc. (on 5B)
IF you try running this example, and get horrific speeds other than what we all are generally getting, THEN we can go in and say this or that or this.

Just too much on the plate to tell now. What if your machine has a memory swap issue? Badly configured? Python outdated? all things like this can severely affect the results/speeds.

From my testing so far I can confirm that the models 5B, fun, i2v - the lot really! all of them preform on my machines roughly the same at around 10 s/it @ 50 steps. There is not a single one that skews outside of these results for me so I can personally say that they all SHOULD be working on your machines as well, between each other, at the same speeds too. [ the H100 is the exception and can make videos in 2min38sec fastest time @ 4s/it ]

So if 5b is running 8 s/it and i2v is doing 18 s/it you got a problem in your i2v config, in this sense you can test to narrow down. (note - you SHOULD have been making different comfyui folders for EACH of these models and not jamming them all into the same repo! yes 45-55gb EACH folder x 3-4 folders eating 150gb+ of hdd space to really see what is what between the models and truly test speeds)

**Comment by kijai** [comment] 2024-09-24 16:39
> (note - you SHOULD have been making different comfyui folders for EACH of these models and not jamming them all into the same repo! yes 45-55gb EACH folder x 3-4 folders eating 150gb+ of hdd space to really see what is what between the models and truly test speeds)

I don't understand what you mean by that, same repo? 45GB? The text encoder isn't used so each 5b model takes ~10GB and 2b model 3.5GB, every possible version (including different GGUF versions) takes ~50GB total currently.

**Comment by KrakeyMTL** [comment] 2024-09-24 17:50
I have folders for each of the versions 5B, i2v etc and each doing their own updates, configs, plugins everything. They all take around 45-50gb each folder, solo by itself to do it's own thing. I do in fact use all the stuff for the model, encoders etc. Possibly why my folders are larger.

That is how I have mine configured so that if one dies it doesn't kill everything else putting me down in the water type thing.

If you, and your configs inside ONE folder have all the models in it, plus the transformers and stuff and total less than 50gb I question what is missing for each. Maybe nothing? Dunno!  Was my 2 cents.  

Kijai, obviously you are getting good speeds n stuff - I doubt that your doing anything wrong LOL. My comment was for more the people having issues - it's very possible not everything is downloaded OR when they are comparing they are missing something VS us two who it seems to work just fine for (your on h100's and home 4090 right?)

I think both you and I have commented literally the same speeds and things across 4-5 threads now. while yo might not use all the files - we both don't know if other people did in fact copy things properly or are using the correct repos and stuff. So more to help out I was stating that a full comfyui + git pull repo clone of any of the models like 5B *should* place you at around 50gb for the entire folder (in windows). if you skip the transformers or use other stuff yeah - will be less!

no shade - just extra info for the others!

Please drop the JSON example you are using that is slow (for the ones having issues) I'll be happy to try YOUR config on my setup and see. if I suddenly get 18 s/it lol we know it's that!

**Comment by kijai** [comment] 2024-09-24 18:04
> I have folders for each of the versions 5B, i2v etc and each doing their own updates, configs, plugins everything. They all take around 45-50gb each folder, solo by itself to do it's own thing. I do in fact use all the stuff for the model, encoders etc. Possibly why my folders are larger.
> 
> That is how I have mine configured so that if one dies it doesn't kill everything else putting me down in the water type thing.
> 
> If you, and your configs inside ONE folder have all the models in it, plus the transformers and stuff and total less than 50gb I question what is missing for each. Maybe nothing? Dunno! Was my 2 cents.
> 
> Kijai, obviously you are getting good speeds n stuff - I doubt that your doing anything wrong LOL. My comment was for more the people having issues - it's very possible not everything is downloaded OR when they are comparing they are missing something VS us two who it seems to work just fine for (your on h100's and home 4090 right?)
> 
> I think both you and I have commented literally the same speeds and things across 4-5 threads now. while you might not use all the files - we both don't know if other people did in fact copy things properly or are using the correct repos and stuff. So more to help out I was stating that a full comfyui + git pull repo clone of any of the models like 5B _should_ place you at around 50gb for the entire folder (in windows). if you skip the transformers or use other stuff yeah - will be less!
> 
> no shade - just extra info for the others!
> 
> @pond or anyone else having speed issues - Please drop the JSON example you are using that is slow (for the ones having issues) I'll be happy to try YOUR config on my setup and see. if I suddenly get 18 s/it lol we know it's that!

Oh you weren't talking about my folder setup? Everything besides the transformers is the same between the models, you do not need each of them to have everything. In Comfy we also use the existing T5 text encoder, which is same for SD3, Flux and CogVideoX, so I'm not storing that in the CogVideoX folders either.

**Comment by rktvr** [comment] 2024-09-24 18:14
offtopic but: which T5 exactly? I'm using a custom/portable install of comfyui and it does not come with a T5, so i downloaded this https://huggingface.co/mcmonkey/google_t5-v1_1-xxl_encoderonly

**Comment by kijai** [comment] 2024-09-24 19:14
> offtopic but: which T5 exactly? I'm using a custom/portable install of comfyui and it does not come with a T5, so i downloaded this https://huggingface.co/mcmonkey/google_t5-v1_1-xxl_encoderonly

That's the one, there's also fp8 version for less memory use if that's an issue, though it's offloaded for the sampling anyway, would mostly affect RAM usage.

**Closed** 2024-10-01 02:08 UTC
