### ISSUE TITLE
I'm using an RTX 4090 GPU to run a 5B model, but I keep getting out-of-memory errors

### ISSUE THREAD

**Issue by longzy1** [kijai/ComfyUI-CogVideoXWrapper#18] opened 2024-08-27 16:30 UTC
I'm using an RTX 4090 GPU to run a 5B model, but I keep getting out-of-memory errors. I'm using the cogvideox_5b_example_01 workflow from the example. What could be the reason?
![image](https://github.com/user-attachments/assets/4ac47cd2-5c50-45fb-9e92-1e2707de07b0)

**Comment by kijai** [comment] 2024-08-27 17:30
On the VAE decode part right? It can be heavy, there's the tiled option in the node now that should help, but I have not yet tested it.

**Comment by progmars** [comment] 2024-08-27 18:00
Do you mean t_tile_length (49) and t_tile_overlap (8) settings? Which one can be safely adjusted and by how much?
Is there any way to quickly test which settings work without waiting for the CogVideo Sampler to fully complete?
It's heartbreaking to see the Sampler completing its job in 20 minutes, and then CogVideo Decode failing with "Allocation on device".

I have a 4060 with 16GB RAM. Wondering why Nvidia shared CUDA memory feature on Windows does not work in this case to overcome the memory limit.

**Comment by kijai** [comment] 2024-08-27 18:28
I mean the tile vae toggle in the decode node, if you don't have that you need to update the nodes

**Comment by progmars** [comment] 2024-08-27 19:05
Ah, thanks, now I have the toggle. However, after the update, now CogVideoSampler started failing with the same error right at the beginning of the process:

```
Error occurred when executing CogVideoSampler:
Allocation on device
```

I made sure that I fully restarted Comfy and that GPU VRAM was empty before hitting Queue Prompt.

**Comment by progmars** [comment] 2024-08-27 19:13
I tried some poking around. When I set fp8_transformer to true or reduce height and width to 200 and 600, I don't have the outofmemory anymore, but another error:

Error occurred when executing CogVideoSampler:
'CogVideoXPipeline' object has no attribute 'guidance_scale'

**Comment by kijai** [comment] 2024-08-27 19:44
> I tried some poking around. When I set fp8_transformer to true or reduce height and width to 200 and 600, I don't have the outofmemory anymore, but another error:
> 
> Error occurred when executing CogVideoSampler: 'CogVideoXPipeline' object has no attribute 'guidance_scale'

That one about guidance_scale I have fixed now.

**Comment by progmars** [comment] 2024-08-27 20:11
@kijai  Thank you so much. I can confirm that with both fp8_transformer and enable_vae_tiling turned on, it completed generating a video on one of the most hated GPUs - 4060 Ti with 16GB VRAM :)

**Comment by kijai** [comment] 2024-08-27 20:25
> @kijai Thank you so much. I can confirm that with both fp8_transformer and enable_vae_tiling turned on, it completed generating a video on one of the most hated GPUs - 4060 Ti with 16GB VRAM :)

Nice, good to know!

**Comment by progmars** [comment] 2024-08-27 21:19
Maybe my happiness was premature... 
Here's one frame from the video I got when running cogvideox_5b_example_01.json with enable_vae_tiling. It's not immediately visible, but when you look closer, there seems to be some kind of a grid all over the frame. Is enable_vae_tiling doing that?

![image](https://github.com/user-attachments/assets/8dc4eebe-a641-459d-ba8f-3c88b087cbbb)

**Comment by kijai** [comment] 2024-08-27 21:32
> Maybe my happiness was premature... Here's one frame from the video I got when running cogvideox_5b_example_01.json with enable_vae_tiling. It's not immediately visible, but when you look closer, there seems to be some kind of a grid all over the frame. Is enable_vae_tiling doing that?
> 
> ![image](https://private-user-images.githubusercontent.com/4199737/361984676-8dc4eebe-a641-459d-ba8f-3c88b087cbbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3OTQ1NDcsIm5iZiI6MTcyNDc5NDI0NywicGF0aCI6Ii80MTk5NzM3LzM2MTk4NDY3Ni04ZGM0ZWViZS1hNjQxLTQ1OWQtYmE4Zi0zYzg4YjA4N2NiYmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjdUMjEzMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTVmNTBiZDc5NTA3ZjY1ZmQwM2IyOTJjMTRlNTIxOWQ0NDZkMGM1MGZjZTFjMjcwZGQyMGZiZTczZmYwMjRiOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t2kbwkOvUzGc9ckZPZxfD10cJa1qTtkQiHUrm6fAmag)

That could very well be, the default settings were like this: 

![image](https://github.com/user-attachments/assets/13557005-787f-40f2-89d9-549d6ebc94d6)

**Comment by progmars** [comment] 2024-08-27 21:34
Ok, so I disabled enable_vae_tiling and kept fp8_transformer enabled, and this seems to be enough to survive the VAE 
"memory jump" without the tiling.

**Closed** 2024-09-04 11:04 UTC

**Comment by icemagno** [comment] 2024-12-23 23:08
Worked when I've reduced the num_frames on VideoSampler
